import sys
import os

# Add parent directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.detectors.api_key_detector import APIKeyDetector
from app.detectors.info_leak_detector import InfoLeakDetector
from app.detectors.ai_code_smell_detector import AICodeSmellDetector

def test_api_key_detection():
    detector = APIKeyDetector()
    sample_content = """
    const awsKey = "AKIA1234567890ABCDEF";
    const openaiKey = "sk-abcdefghijklmnopqrstT3BlbkZJ1234567890abcdefghij";
    const publicStripe = "pk_live_1234567890abcdefghijklmn";
    const secretStripe = "sk_live_1234567890abcdefghijklmn";
    """
    findings = detector.detect(sample_content, "test.js")
    
    titles = [f["title"] for f in findings]
    assert "AWS Access Key" in titles
    assert "OpenAI Key" in titles
    assert "Stripe Key" in titles
    
    # Check severity for Stripe
    for f in findings:
        if "pk_live" in f["masked_value"]:
             assert f["severity"] == "Low"
        if "sk_live" in f["masked_value"]:
             assert f["severity"] == "Critical"
    
    print("API Key Detection Test Passed!")

def test_info_leak_detection():
    detector = InfoLeakDetector()
    sample_content = """
    // Source map: //# sourceMappingURL=main.js.map
    const dbUrl = "http://localhost:5432/mydb";
    const adminUrl = "/admin/dashboard";
    console.log("Found user secret: " + secret);
    """
    findings = detector.detect(sample_content, "test.js")
    
    titles = [f["title"] for f in findings]
    assert "Source Map Reference" in titles
    assert "Internal IP Address" in titles
    assert "Admin Panel Route" in titles
    assert "Console Debug" in titles
    
    print("Info Leak Detection Test Passed!")

def test_ai_smell_detection():
    detector = AICodeSmellDetector()
    sample_content = """
    const apiKey = "YOUR_API_KEY_HERE"; // temporary key for demo
    // The following code was generated by an LLM
    db.connect("mongodb://dbuser:dbpass@localhost:27017/test");
    """
    findings = detector.detect(sample_content, "test.js")
    
    titles = [f["title"] for f in findings]
    assert "Insecure Placeholder" in titles
    assert "Temporary Secret Comment" in titles
    assert "Direct Database Call" in titles
    
    print("AI Code Smell Detection Test Passed!")

if __name__ == "__main__":
    test_api_key_detection()
    test_info_leak_detection()
    test_ai_smell_detection()
    print("\nAll Backend Detector Tests Passed Successfully!")
